language: php
php:
  - 7.1
  - 7.2
matrix:
   fast_finish: true
services:
  - mysql
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - sudo apt-get update -qq

install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.4.0" --quiet --no-interaction
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE yii2_ext_test;'
  - php tests/yii migrate/up --interactive=0

script: phpunit -vvv
